# Generated by Django 5.0.7 on 2024-08-03 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Championship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('war_cry', models.CharField(max_length=100)),
                ('foundation_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('score_a', models.PositiveIntegerField(default=0)),
                ('score_b', models.PositiveIntegerField(default=0)),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_championship.championship')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='start_championship.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='start_championship.team')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='start_championship.team')),
            ],
        ),
        migrations.AddField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(to='start_championship.team'),
        ),
    ]
