# Generated by Django 5.0.7 on 2024-08-04 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_team', '0001_initial'),
        ('start_championship', '0003_alter_match_team_a_alter_match_team_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championship',
            name='name',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='started',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_number',
        ),
        migrations.AddField(
            model_name='championship',
            name='current_phase',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='championship',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_championships', to='register_team.team'),
        ),
        migrations.AlterField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(related_name='championships', to='register_team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='start_championship.championship'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='register_team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='register_team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='register_team.team'),
        ),
    ]
