# Generated by Django 5.0.7 on 2024-08-04 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start_championship', '0004_remove_championship_name_remove_championship_started_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='championship',
            name='current_phase',
        ),
        migrations.RemoveField(
            model_name='championship',
            name='winner',
        ),
        migrations.AddField(
            model_name='championship',
            name='name',
            field=models.CharField(default='Untitled Pair', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='round_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='match',
            name='championship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_championship.championship'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_b',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(to='start_championship.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='start_championship.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='start_championship.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='start_championship.team'),
        ),
    ]
