# Generated by Django 5.0.7 on 2024-08-04 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register_team', '0001_initial'),
        ('start_championship', '0007_alter_championship_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a_matches', to='register_team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='register_team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b_matches', to='register_team.team'),
        ),
        migrations.RemoveField(
            model_name='match',
            name='championship',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_number',
        ),
        migrations.AlterField(
            model_name='championship',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='championship',
            name='teams',
            field=models.ManyToManyField(to='register_team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_a',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score_b',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('championship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_championship.championship')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='start_championship.round'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
